ALTER TABLE services ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'draft' NOT NULL;
ALTER TABLE services ADD COLUMN IF NOT EXISTS build_command TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS run_command TEXT;
