// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package dashboard

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"servicemanager/internal/models"
	"servicemanager/internal/views/layouts"
	viewsServices "servicemanager/internal/views/services"
	viewsUsers "servicemanager/internal/views/users"
)

func Dashboard(
	currentUser models.User,
	usersList []models.User,
	invites []models.Invite,
	servicesList []models.Service,
	githubRepos []models.GithubRepo,
	githubInstalled bool,
	githubAuthURL string,
	inviteError string,
	serviceError string,
) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Header --> <div class=\"d-flex justify-content-between align-items-center mb-4 pb-3 border-bottom\"><div><h1 class=\"h3 mb-0\">Service Manager</h1><p class=\"text-muted mb-0\">Logged in as: <strong>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(currentUser.Email)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/dashboard/dashboard.templ`, Line: 26, Col: 72}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</strong> (<span class=\"badge bg-primary\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(string(currentUser.UserRole))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/dashboard/dashboard.templ`, Line: 26, Col: 146}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span>)</p></div><div><form method=\"POST\" action=\"/logout\"><button type=\"submit\" class=\"btn btn-outline-danger\">Logout</button></form></div></div><!-- Nav Tabs --> <ul class=\"nav nav-tabs\" id=\"dashboardTabs\" role=\"tablist\"><li class=\"nav-item\" role=\"presentation\"><button class=\"nav-link active\" id=\"services-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#services\" type=\"button\" role=\"tab\" aria-controls=\"services\" aria-selected=\"true\">Services</button></li><li class=\"nav-item\" role=\"presentation\"><button class=\"nav-link\" id=\"users-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#users\" type=\"button\" role=\"tab\" aria-controls=\"users\" aria-selected=\"false\">Users</button></li></ul><!-- Tab Content --> <div class=\"tab-content\" id=\"dashboardTabsContent\"><!-- Services Tab --><div class=\"tab-pane fade show active\" id=\"services\" role=\"tabpanel\" aria-labelledby=\"services-tab\"><div class=\"row pt-3\"><!-- Left: Add Service Form (Admins only) -->")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if currentUser.UserRole == models.RoleAdmin {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"col-md-4\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if serviceError != "" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"alert alert-danger\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var5 string
					templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(serviceError)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/dashboard/dashboard.templ`, Line: 54, Col: 54}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = viewsServices.AddServiceForm(githubRepos, githubInstalled, githubAuthURL).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><div class=\"col-md-8\"><div class=\"card shadow-sm\"><div class=\"card-body\"><h5 class=\"card-title mb-3\">Configured Services</h5><div id=\"services-list-container\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = viewsServices.ServicesTable(servicesList, true).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div></div></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div class=\"col-md-12\"><div class=\"card shadow-sm\"><div class=\"card-body\"><h5 class=\"card-title mb-3\">Configured Services</h5>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = viewsServices.ServicesTable(servicesList, false).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div></div><!-- Users Tab --><div class=\"tab-pane fade\" id=\"users\" role=\"tabpanel\" aria-labelledby=\"users-tab\"><div class=\"row pt-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if currentUser.UserRole == models.RoleAdmin {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<!-- Invite User (Admins only) --> <div class=\"col-md-4\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if inviteError != "" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<div class=\"alert alert-danger\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var6 string
					templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(inviteError)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/dashboard/dashboard.templ`, Line: 88, Col: 53}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</div>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<div class=\"card shadow-sm mb-4\"><div class=\"card-body\"><h5 class=\"card-title mb-3\">Invite User</h5><form method=\"POST\" action=\"/users/invite\"><div class=\"mb-3\"><label for=\"invite_email\" class=\"form-label\">Email address</label> <input type=\"email\" class=\"form-control\" id=\"invite_email\" name=\"email\" required placeholder=\"user@example.com\"></div><button type=\"submit\" class=\"btn btn-success w-100\">Send Invitation</button></form></div></div><div class=\"card shadow-sm\"><div class=\"card-body\"><h5 class=\"card-title mb-3\">Pending Invitations</h5>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = viewsUsers.InvitesTable(invites, true).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</div></div></div><div class=\"col-md-8\"><div class=\"card shadow-sm\"><div class=\"card-body\"><h5 class=\"card-title mb-3\">Registered Users</h5>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = viewsUsers.UsersTable(usersList, currentUser.ID, true).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "</div></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "<div class=\"col-md-12\"><div class=\"card shadow-sm\"><div class=\"card-body\"><h5 class=\"card-title mb-3\">Registered Users</h5>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = viewsUsers.UsersTable(usersList, currentUser.ID, false).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</div></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "</div></div></div><!-- Github Connect Modal --> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if currentUser.UserRole == models.RoleAdmin && !githubInstalled {
				templ_7745c5c3_Err = viewsServices.GithubConnectModal(githubAuthURL).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, " <script>\n\t\t\tdocument.addEventListener(\"DOMContentLoaded\", function() {\n\t\t\t\tvar hash = window.location.hash;\n\t\t\t\tif (hash) {\n\t\t\t\t\tvar tabElement = document.querySelector('button[data-bs-target=\"' + hash + '\"]');\n\t\t\t\t\tif (tabElement) {\n\t\t\t\t\t\tvar tab = new bootstrap.Tab(tabElement);\n\t\t\t\t\t\ttab.show();\n\t\t\t\t\t}\n\t\t\t\t}\n\n\t\t\t\t// Update URL hash when a tab changes\n\t\t\t\tvar tabEls = document.querySelectorAll('button[data-bs-toggle=\"tab\"]');\n\t\t\t\ttabEls.forEach(function(el) {\n\t\t\t\t\tel.addEventListener('shown.bs.tab', function(e) {\n\t\t\t\t\t\tvar target = e.target.getAttribute(\"data-bs-target\");\n\t\t\t\t\t\tif (history.replaceState) {\n\t\t\t\t\t\t\thistory.replaceState(null, null, target);\n\t\t\t\t\t\t} else {\n\t\t\t\t\t\t\tlocation.hash = target;\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\t\t\t\t});\n\t\t\t});\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Layout("Dashboard").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
